- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: present
  become: true
  
- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
    update_cache: true

- name: Add Docker official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker
  ansible.builtin.apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
    update_cache: true

- name: Check Docker installation
  ansible.builtin.command: docker --version
  register: docker_version
  failed_when: '"Docker version" not in docker_version.stdout'

- name: Install Docker Python library
  ansible.builtin.pip:
    name: docker

- name: Create a network
  community.docker.docker_network:
    name: my-network
    state: present