- name: Install pip
  ansible.builtin.apt:
    name: ["python3-dev", "python3-setuptools", "python3-pip"]
    state: latest
    
- name: Update pip
  ansible.builtin.pip:
    name: ["pip", "openstacksdk"]
    state: latest

- name: Ensure openstacksdk is installed
  pip:
    name: openstacksdk
    state: present

- name: Install Git
  apt:
    name: 
      - git
      - nodejs
    state: present